[workspace]
members = [
    "battleship",
    "battleship_cli",
    "battleship_web",
]
resolver = "2"

[workspace.package]
authors = ["Aaron Mathews <aamathews23@gmail.com>"]
homepage = "https://github.com/aamathews23/battleship-rs"
readme = "README.md"
repository = "https://github.com/aamathews23/battleship-rs"
edition = "2021"
