[package]
name = "battleship_web"
version = "0.1.0"
description = "simple web game consuming the `battleship` library package."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
battleship = { version = "0.1.0", path = "../battleship" }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
